publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "joint_trajectory_position_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [0, 0.785, 0.0, 0.0, 0.0, 0.0]
    pos2: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    pos3: [0, -0.785, 0.0, 0.0, 0.0, 0.0]
    pos4: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      joint1: [-0.1,0.1]
      joint2: [-0.1,0.1]
